### ISSUE TITLE
Add WASM standalone builds

### ISSUE THREAD

**Issue by ajalt** [paulocoutinhox/pdfium-lib#137]
Thanks for your work on this project!

Would you consider adding building a new wasm-wasi artifact that's compiled with emscripten's [standalone][1] mode?

I'm trying to use pdfium in a wasm engine like wasmtime or wasmer which can't use the JS shims that the current wasm build requires.

[1]: https://emscripten.org/docs/tools_reference/settings_reference.html#standalone-wasm

**Comment by paulocoutinhox** [comment]
Hi,

What is the steps to i understand how to build it.

**Comment by ajalt** [comment]
I was able to get it to build with this:

```diff
diff --git a/modules/wasm.py b/modules/wasm.py
--- a/modules/wasm.py
+++ b/modules/wasm.py
@@ -657,6 +657,11 @@ def run_task_generate():
                 "ASSERTIONS=1",
                 "-s",
                 "ALLOW_MEMORY_GROWTH=1",
+                "-sSTANDALONE_WASM=1",
+                "-sWASM_ASYNC_COMPILATION=0",
+                "-sWARN_ON_UNDEFINED_SYMBOLS=1",
+                "-sERROR_ON_UNDEFINED_SYMBOLS=0",
                 "-sMODULARIZE",
                 "-sEXPORT_NAME=PDFiumModule",
                 "-std=c++11",
```

But I'm not sure if it's better to patch the undefined symbols instead of ignoring them like that.

**Comment by paulocoutinhox** [comment]
We have:

<img width="149" alt="image" src="https://github.com/user-attachments/assets/4829859c-046f-4c7c-a6c0-749c7e6f809c">

What name you suggest for it?

**Comment by paulocoutinhox** [comment]
And more two questions:

- Why we need care about undefined symbols in this case?
- How i can test the stand alone wasm?

**Comment by ajalt** [comment]
I'm not sure if the undefined symbols are used for anything, which is why I ignored them.

If you want to call some functions in the library to test, here's an example that uses wasmtime with rust:

```rust
use wasmtime::*;
use wasmtime_wasi::*;

let engine = Engine::default();
let module = Module::from_file(&engine, "pdfium.wasm")?;
let mut linker = Linker::new(&engine);
wasmtime_wasi::preview1::add_to_linker_sync(&mut linker, |s| s)?;
linker.define_unknown_imports_as_default_values(&module)?;
let pre = linker.instantiate_pre(&module)?;
let wasi_ctx = WasiCtxBuilder::new().build_p1();
let mut store = Store::new(&engine, wasi_ctx);
let instance = pre.instantiate(&mut store)?;
let init_library = instance.get_typed_func::<(), ()>(&mut store, "FPDF_InitLibrary")?;
init_library.call(&mut store, ())?;
let get_last_error = instance.get_typed_func::<(), i32>(&mut store, "FPDF_GetLastError")?;
println!("result={}", get_last_error.call(&mut store, ())?);
```

wasmtime also has python bindings that should work the same way

**Comment by paulocoutinhox** [comment]
Hi,

I have added but get error:
https://github.com/paulocoutinhox/pdfium-lib/pull/140/files

Error:

```
python3 make.py test-wasmtime                                                                               
Testing with wasmtime...
Traceback (most recent call last):
  File "/Users/paulo/Developer/workspaces/cpp/pdfium-lib/make.py", line 250, in <module>
    main(args)
  File "/Users/paulo/Developer/workspaces/cpp/pdfium-lib/make.py", line 217, in main
    wasm.run_task_test_wasmtime()
  File "/Users/paulo/Developer/workspaces/cpp/pdfium-lib/modules/wasm.py", line 567, in run_task_test_wasmtime
    instance = linker.instantiate(store, module)
  File "/opt/homebrew/lib/python3.10/site-packages/wasmtime/_linker.py", line 171, in instantiate
    raise WasmtimeError._from_ptr(error)
wasmtime._error.WasmtimeError: unknown import: `env::invoke_viii` has not been defined
```

Do you know what can be wrong?

Thanks.

**Comment by ajalt** [comment]
Thank you for looking into this!

Emscripten adds some functions like that to the compiled WASM file. I'm not sure if it's possible to
stop it from doing that, but it doesn't seem like actually used by pdfium, so it defining them as empty stubs 
should work.

In the rust example I posted, that's what `linker.define_unknown_imports_as_default_values` does.

The python bindings don't look like they have a similar function, but we can do it manually with
something like this:

```python
def define_unknown_imports_as_default_values(linker: Linker, module: Module) -> None:
    for imp in module.imports:
        if imp.module != "env":
            continue
        if isinstance(imp.type, wasmtime.FuncType):
            func_ty = imp.type
            result_tys = func_ty.results

            def default_func(*args):
                # XXX: For some reason _emscripten_throw_longjmp is called with different numbers of
                # arguments, and sometimes expects a return value and sometimes not. This feels like
                # a bug, but I don't know if it's in emscripten or wasmtime.
                if imp.name == "_emscripten_throw_longjmp":
                    if len(args) in (3, 5):
                        return 0
                    return None
                results = []
                for ty in result_tys:
                    match ty:
                        case ValType.i32():
                            results.append(0)
                        case ValType.i64():
                            results.append(0)
                        case ValType.f32():
                            results.append(0.0)
                        case ValType.f64():
                            results.append(0.0)
                return results

            linker.define_func(imp.module, imp.name, func_ty, default_func)

engine = Engine()
module = Module.from_file(engine, "pdfium.wasi.wasm")
store = Store(engine)
linker = Linker(engine)
linker.define_wasi()
wasi_config = WasiConfig()
wasi_config.inherit_stdout()
store.set_wasi(wasi_config)
_define_unknown_imports_as_default_values(linker, module)
instance = linker.instantiate(store, module)
instance.exports(store)["FPDF_InitLibrary"](store)
```

That's kind of hacky, but it seems to work.

**Comment by paulocoutinhox** [comment]
Nice.

Do you have the commands to test the rust code?

Thanks.

**Comment by ajalt** [comment]
To run that rust code, you'd need a `Cargo.toml` something like this:

```toml
[package]
name = "rust_wasm_test"
version = "0.1.0"
edition = "2021"

[dependencies]
wasmtime = "=24.0.0"
wasmtime-wasi = "=24.0.0"
```

Put the `pdfium.wasm` file in the same directory as the `Cargo.toml` file and add the above rust code to `src/main.rs`.

Then you'd run `cargo build --release` to build the binary, and you'd run it with
`./target/release/rust_wasm_test`.

**Comment by yslflow** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by paulocoutinhox** [comment]
💙 **Support the Project** 🚀

If this project has been helpful to you and your projects, please consider supporting its development with a donation on GitHub 🙏

Your support helps keep the project alive, maintained, and continuously improved — from bug fixes 🐛 to new features ✨ and better documentation 📘.

Every contribution, no matter the size, makes a big difference 💪
Thank you for being part of the community and for supporting open source ❤️

👉 Donate here: [https://github.com/paulocoutinhox/pdfium-lib](https://github.com/paulocoutinhox/pdfium-lib)

🚀 Together, we can make this project even better!
