### ISSUE TITLE
Build script seems broken by change of pygemstones.

### ISSUE THREAD

**Issue by kitanic** [paulocoutinhox/pdfium-lib#74]
I tried to build pdfium for iOS as per instructions and got the following error. This seems to be due to changes made to pygemstones a few days ago.

```
Building libraries...
Generating files to arch "arm" and configuration "release"...
Traceback (most recent call last):
  File "make.py", line 241, in <module>
    main(args)
  File "make.py", line 116, in main
    ios.run_task_build()
  File "****/pdfium-lib/modules/ios.py", line 443, in run_task_build
    r.run_as_shell(" ".join(command))
AttributeError: module 'pygemstones.system.runner' has no attribute 'run_as_shell'

```

I tried modifying run_as_shell to run(command, shell=True), but now I get the following error. I am not familiar with pythons so I don't know any better.

```
Building libraries...
Generating files to arch "arm" and configuration "release"...
ERROR No command specified.
Most commonly you want "gn gen <out_dir>" to make a build dir.
Or try "gn help" for more commands.
COMMAND: gn gen out/ios-arm-release --args='target_os="ios" target_cpu="arm" use_goma=false is_debug=false pdf_use_skia=false pdf_use_skia_paths=false pdf_enable_xfa=false pdf_enable_v8=false is_component_build=false clang_use_chrome_plugins=false pdf_is_standalone=false ios_deployment_target="9.0" ios_enable_code_signing=false use_xcode_clang=true pdf_is_complete_lib=true use_custom_libcxx=false enable_ios_bitcode=true arm_use_neon=false symbol_level=0'
WORKING DIR: None
[ERROR] Command execution has failed
```

**Comment by paulocoutinhox** [comment]
Hi,

Im fixing all projects.

Im some minutes it will be ready here.

**Comment by kitanic** [comment]
Thanks for the reply. I'm waiting for it to be fixed!

**Comment by paulocoutinhox** [comment]
Hi,

I made a pull-request:
https://github.com/paulocoutinhox/pdfium-lib/pull/75

I will go wait it build without problems and merge.

**Comment by paulocoutinhox** [comment]
Hi,

It was fixed and released.

Feel free to support the development.

Thanks.

**Comment by kitanic** [comment]
The build was successful. 
Thanks for responding so quickly!

**Comment by paulocoutinhox** [comment]
Nice! I will close it.

https://github.com/sponsors/paulocoutinhox
